---
- hosts: all
  become: yes
  tasks:
        - name: Install sysdig
          shell: |
                  curl -s https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public | apt-key add -
                  curl -s -o /etc/apt/sources.list.d/draios.list http://download.draios.com/stable/deb/draios.list
                  apt-get update
                  apt-get -y install linux-headers-$(uname -r)
                  exit 0

        - name: Install linux sysdig
          apt: name=sysdig state=latest
